spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.error.include-message=always
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sportfolio}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sportfolio}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sportfolio}
rapidapi.key=${RAPIDAPI_KEY}
server.port=${PORT:8080}