spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/sportfolio
spring.datasource.username=sportfolio
spring.datasource.password=sportfolio
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rapidapi.key=8e90bc6ff7mshfd19c1967342824p1d6dc1jsnb0bd2f21a017
server.error.include-message=always