spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.error.include-message=always
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN

google.client.id=513691614846-11doh17hg04q3mrhmmqbj9oc892sff3u.apps.googleusercontent.com